src/Entity/Event.php
<?php
namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use MyCLabs\Enum\Enum;

/**
 * Class Event
 * @package App\Entity
 *
 * @ORM\Entity
 */
class Event extends KnowledgePoint {
    /** @ORM\Column(type="string") */
    private $type;

    /** @ORM\Column(type="text") */
    private $topic = '';

    /** @ORM\Column(type="text") */
    private $text = '';

    /** @ORM\Column(type="dateinterval") */
    private $duration;

    /**
     * @ORM\OneToMany(
     *     targetEntity="ZimmEntry",
     *     mappedBy="parent_event",
     *     cascade={"persist", "remove"},
     *     orphanRemoval=true,
     * )
     * TODO: Add the complicated getters and setters
     */
    private $zimm_entries;

    /** @ORM\Column(type="string", nullable=true) */
    private $title;

    public function getTitle() : ?string {
        return $this->title;
    }

    public function setTitle(?string $title) : self {
        $this->title = $title;
        return $this;
    }

    public function getText() : string {
        return $this->text;
    }

    public function setText(string $text) : self {
        $this->text = $text;
        return $this;
    }

    public function getTopic() : string {
        return $this->topic;
    }

    public function setTopic(string $topic) : self {
        $this->topic = $topic;
        return $this;
    }

    public function updateDuration(\DateInterval $diff) : self {
        $this->duration = self::addDateIntervals($this->duration, $diff);

        return $this;
    }

    public function getDuration() : \DateInterval {
        return $this->duration;
    }

    public function getType() : EventType {
        return new EventType($this->type);
    }

    public function setType(EventType $type) : self {
        $this->type = $type->getValue();
        return $this;
    }

    public function getZimmEntries() : Collection {
        return $this->zimm_entries;
    }

    /**
     * @throws \Exception
     */
    public function setSection(Section $section) : KnowledgePoint {
        throw new \Exception('Section can not be changed for Event instances.');
    }

    public function __construct() {
        parent::__construct();
        $this->zimm_entries = new ArrayCollection();
        $this->duration = new \DateInterval('PT0S');
        $this->type = EventType::WORKSHOP();
    }

    public function addZimmEntry(ZimmEntry $entry) {
        $this->zimm_entries->add($entry);
        $entry->setParentEvent($this);
        $this->duration = key($entry->getEventDay()) < 1 ? self::addDateIntervals($this->duration, $entry->getDuration()) : new \DateInterval('P' . key($entry->getEventDay()) . 'D');
    }

    public function removeZimmEntry(ZimmEntry $entry) {
        $this->zimm_entries->removeElement($entry); // TODO: Check if it is removed and existed before that
        $this->duration = self::subDateIntervals($this->duration, $entry->getDuration());
    }

    public function removeZimmEntryByKey($key) {
        $this->duration = self::subDateIntervals($this->duration, $this->zimm_entries[$key]->getDuration());
        $this->zimm_entries->remove($key);
    }

    public static function addDateIntervals(\DateInterval $a, \DateInterval $b) {
        $reference = new \DateTime();
        $endTime = clone $reference;

        $endTime->add($a);
        $endTime->add($b);

        return $reference->diff($endTime);
    }

    public static function subDateIntervals(\DateInterval $a, \DateInterval $b) {
        $reference = new \DateTime();
        $endTime = clone $reference;

        $endTime->add($a);
        $endTime->sub($b);

        return $reference->diff($endTime);
    }
}

/**
 * Class EventType
 * @package App\Entity
 * @method static EventType SEMINAR
 * @method static EventType WORKSHOP
 * @method static EventType GROUP_MEETING
 */
class EventType extends Enum {
    private const SEMINAR = "Seminar";
    private const WORKSHOP = "Workshop";
    private const GROUP_MEETING = "Gruppenstunde";
}

src/Entity/KnowledgePoint.php
<?php
namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use MyCLabs\Enum\Enum;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Class KnowledgePoint
 * @package App\Entity
 *
 * @ORM\Entity
 * @ORM\Entity(repositoryClass="App\Repository\KnowledgePointRepository")
 * @ORM\InheritanceType("JOINED")
 * @ORM\DiscriminatorColumn(name="discr", type="string")
 * @ORM\DiscriminatorMap({"knowledge_point" = "KnowledgePoint", "activity" = "Activity", "event" = "Event"})
 * @ORM\HasLifecycleCallbacks
 */
class KnowledgePoint {
    /** @ORM\Id @ORM\Column(type="integer") @ORM\GeneratedValue  */
    private $id;

    /** @ORM\Column(type="simple_array", nullable=true) */
    private $tags = [];

    /** @ORM\Column(type="integer") */
    private $min_age;

    /** @ORM\Column(type="integer") */
    private $max_age;

    /** @ORM\Column(type="integer") */
    private $difficulty = 0;

    /** @ORM\Column(type="text") */
    private $comment = '';

    /**
     * @ORM\ManyToOne(targetEntity="User")
     * @ORM\JoinColumn(name="owner_id", referencedColumnName="id")
     */
    private $owner;

    /**
     * @ORM\ManyToOne(targetEntity="Category")
     * @ORM\JoinColumn(name="category_id", referencedColumnName="id")
     */
    private $category;

    /**
     * @ORM\Column(type="integer")
     */
    private $visibility;

    /**
     * @ORM\Column(type="integer")
     */
    private $state;

    /** @ORM\Column(type="datetime") */
    private $createdAt;

    /** @ORM\Column(type="datetime") */
    private $updatedAt;

    /** @ORM\Column(type="string", length=12) */
    private $section;

    public function getAge() : array {
        return ['min' => $this->min_age, 'max' => $this->max_age];
    }

    public function setAge(array $age_range) : self {
        $this->min_age = $age_range['min'];
        $this->max_age = $age_range['max'];
        return $this;
    }

    public function getOwner() : ?User {
        return $this->owner;
    }

    public function setOwner(User $owner) : self {
        $this->owner = $owner;
        return $this;
    }

    public function getVisibility() : Visibility {
        return new Visibility($this->visibility);
    }

    public function setVisibility(Visibility $visibility) : self {
        $this->visibility = $visibility->getValue();
        return $this;
    }

    public function getState() : ModerationState {
        return new ModerationState($this->state);
    }

    public function setState(ModerationState $state) : self {
        $this->state = $state->getValue();
        return $this;
    }

    public function getTags() : array {
        return $this->tags;
    }

    public function setTags(array $tags) : self {
        $this->tags = $tags;
        return $this;
    }

    public function getDifficulty() : int {
        return $this->difficulty;
    }

    public function setDifficulty(int $difficulty) : self {
        $this->difficulty = $difficulty;
        return $this;
    }

    public function getComment() : string {
        return $this->comment;
    }

    public function setComment(string $comment) : self {
        $this->comment = $comment;
        return $this;
    }

    public function getCategory() : ?Category {
        return $this->category;
    }

    public function setCategory(Category $category) : self {
        $this->category = $category;
        return $this;
    }

    public function getId() : int {
        return $this->id;
    }

    public function getUpdatedAt() : \DateTime {
        return $this->updatedAt;
    }

    public function getCreatedAt() : \DateTime {
        return $this->createdAt;
    }

    public function setSection(Section $section) : self {
        $this->section = $section->getValue();
        return $this;
    }

    public function getSection() : Section {
        return new Section($this->section);
    }

    public function __construct() {
        // Set Defaults
        $this->visibility = Visibility::PRIVATE();
        $this->state = ModerationState::UNMODERATED();
        $this->section = Section::EDUCATION();
    }

    /**
     * @ORM\PrePersist
     */
    public function onPrePersist() : void {
        $this->createdAt = new \DateTime();
        $this->updatedAt = $this->createdAt;
    }

    /**
     * @ORM\PreUpdate
     */
    public function onPreUpdate() : void {
        $this->updatedAt = new \DateTime();
    }

    public function getClass() {
        return get_class($this);
    }
}

/**
 * Class Visibility
 * @package App\Entity
 * @method static Visibility PUBLIC
 * @method static Visibility PRIVATE
 * @method static Visibility AUTHENTICATED
 */
class Visibility extends Enum {
    private const PUBLIC = 0;
    private const PRIVATE = 1;
    private const AUTHENTICATED = 2;
}

/**
 * Class ModerationState
 * @package App\Entity
 * @method static ModerationState UNMODERATED
 * @method static ModerationState MODERATION_PENDING
 * @method static ModerationState PUBLISHED
 */
class ModerationState extends Enum {
    private const UNMODERATED = 0;
    private const MODERATION_PENDING = 1;
    private const PUBLISHED = 2;
}

/**
 * Class Section
 * @package App\Entity
 * @method static Section THEORY
 * @method static Section EDUCATION
 * @method static Section ORGANISATION
 */
class Section extends Enum {
    private const THEORY = 'theory';
    private const EDUCATION = 'education';
    private const ORGANISATION = 'organisation';
}

src/Form/Type/EventType.php
<?php

namespace App\Form\Type;

use App\Entity\ZimmEntry;
use Psr\Log\LoggerInterface;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\DateIntervalType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Contracts\Translation\TranslatorInterface;

class EventType extends AbstractType {
    private $t;
    private $logger;

    public function __construct(TranslatorInterface $t, LoggerInterface $logger) {
        $this->t = $t;
        $this->logger = $logger;
    }

    public function buildForm(FormBuilderInterface $builder, array $options) {
        $t = $this->t;

        $builder
            ->add('type', EnumType::class, [
                'enum_class' => \App\Entity\EventType::class,
                'label' => 'event.meta.type',
                'required' => true,
            ])
            ->add('topic', TextType::class, [
                'attr' => [
                    'placeholder' => 'event.meta.topic'
                ],
                'label' => false,
                'required' => false,
            ])
            ->add('text', QuillType::class, [
                'placeholder' => $t->trans('event.form.text_placeholder'),
                'label' => 'event.content.text',
                'required' => false,
            ])
            ->add('zimm_entries', CollectionType::class, [
                'entry_type' => ZimmEntryType::class,
                'by_reference' => false,
                'prototype' => true,
                'allow_add' => true,
                'allow_delete' => true,
                'prototype_data' => new ZimmEntry(),
                'label' => 'zimm_entry.plural',
                'required' => false,
            ])
        ;
    }

    public function getParent() {
        return KnowledgePointType::class;
    }
}

src/Controller/EventController.php
<?php

namespace App\Controller;

use App\Entity\Event;
use App\Form\Type\EventType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/event")
 */
class EventController extends AbstractController {

    public function __construct() {
    }

    /**
     * @Route("/", name="event_index", methods={"GET"})
     */
    public function index() : Response {
        $events = $this->getDoctrine()
            ->getRepository(Event::class)
            ->findAll();

        return $this->render('event/list.html.twig', [
            'events' => $events,
            'current_topic' => 'education',
        ]);
    }

    /**
     * @Route("/new", name="event_new", methods={"GET","POST"})
     */
    public function new(Request $request) : Response {
        $event = new Event();
        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($event);
            $entityManager->flush();

            return $this->redirectToRoute('event_show', ['id' => $event->getId()]);
        }

        return $this->render('event/new.html.twig', [
            'event' => $event,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="event_show", methods={"GET"})
     */
    public function show(Event $event) : Response {
        return $this->render('event/show.html.twig', [
            'event' => $event,
            'current_topic' => 'education',
        ]);
    }

    /**
     * @Route("/{id}/edit", name="event_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Event $event) : Response {
        $form = $this->createForm(eventType::class, $event);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('event_show', [
                'id' => $event->getId(),
            ]);
        }

        return $this->render('event/edit.html.twig', [
            'event' => $event,
            'form' => $form->createView(),
            'current_topic' => 'education',
        ]);
    }

    /**
     * @Route("/{id}", name="event_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Event $event) : Response {
        if($this->isCsrfTokenValid('delete' . $event->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($event);
            $entityManager->flush();
        }

        return $this->redirectToRoute('event_index');
    }
}

templates/event/_card.html.twig
{% if not entry is null %}
    {% set id = id|default('zimm_entry-' ~ entry.id) %}
    {% set title = title|default(entry.title) %}
    {% set type = type|default(entry.type) %}
    {% set duration = duration|default(entry.duration) %}
    {% set goal = goal|default(entry.goal) %}
    {% set description = description|default(entry.description) %}
    {% set activity = activity|default(entry.activity) %}
    {% set materialList = materialList|default(entry.materialList) %}
{% endif %}

<div id="{{ id }}" class="card zimm_entry-card {{ is_form ? 'zimm_entry-form' : 'l' }}">
    <div class="card-header" data-toggle="collapse" data-target="#{{ id }}-content" aria-expanded="false" aria-controls="{{ id }}-content">
        {% block zimm_entry_title %}
            <div class="zimm_entry-duration">{{ duration ? duration.format('%H:%I') : '' }}</div>
            <h3 class="zimm_entry-title">{{ title }}</h3>
        {% endblock %}
    </div>
    <div id="{{ id }}-content" class="collapse">
        {% if is_form|default(false) or (not goal is empty) %}
            <ul class="list-group list-group-flush">
                {% block zimm_entry_goal %}
                    <li class="list-group-item"><strong>{{ 'zimm_entry.goal.label'|trans }}</strong>: {{ goal }}</li>
                {% endblock %}
            </ul>
        {% endif %}
        {% if is_form|default(false) or (not description is empty) %}
            <ul class="list-group list-group-flush">
                <li class="list-group-item list-group-item-action" data-toggle="collapse" data-target="#{{ id }}-desc" aria-expanded="false" aria-controls="{{ id }}-desc"><h4>{{ ('zimm_entry.description.label.' ~ type|default('Custom'))|trans }}</h4></li>
            </ul>
            <div class="collapse" id="{{ id }}-desc">
                <div class="card-body" >
                    {% block zimm_entry_description %}
                        {% spaceless %}
                        <pre class="card-text zimm_entry-description">{{ description }}</pre>
                        {% endspaceless %}
                    {% endblock %}
                </div>
            </div>
        {% endif %}
        {% if is_form|default(false) or ((not materialList is empty) and (not materialList|first == '')) %}
            <ul class="list-group list-group-flush">
                <li class="list-group-item list-group-item-action" data-toggle="collapse" data-target="#{{ id }}-material" aria-expanded="false" aria-controls="{{ id }}-material"><h4>{{ 'zimm_entry.material.label'|trans }}</h4></li>
            </ul>
            <div class="collapse" id="{{ id }}-material">
                <div class="card-body" >
                    {% block zimm_entry_material %}
                        <ul>
                            {% for material in materialList %}
                                {% if not material is empty %}<li>{{ material }}</li>{% endif %}
                            {% endfor %}
                        </ul>
                    {% endblock %}
                </div>
            </div>
        {% endif %}
        {% if is_form|default(false) or activity %}
            <div class="card-footer clearfix">
                {% block zimm_entry_controls %}
                    {% if activity %}<a class="btn btn-info" href="{{ path('activity_show', {'id': activity.id}) }}">{{ ('zimm_entry.activity.show.' ~ activity.type)|trans }}</a>{% endif %}
                {% endblock %}
            </div>
        {% endif %}
    </div>
</div>

templates/event/_delete_form.html.twig
<form method="post" action="{{ path('event_delete', {'id': event.id}) }}" onsubmit="return confirm('Bist du sicher, dass du das Event löschen möchtest?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ event.id) }}">
    <button class="btn">Löschen</button>
</form>

templates/event/_form.html.twig
{% extends 'form/knowledge_point.common.html.twig' %}

{% block form_content %}
    {{ form_row(form.topic) }}
    {{ form_row(form.text) }}
    <div class="row">
        <div class="col-6">
            {{ form_row(form.age) }}
            {{ form_row(form.difficulty) }}
        </div>
        <div class="col-6">
            {{ form_row(form.comment) }}
        </div>
    </div>
    {{ form_row(form.zimm_entries) }}
{% endblock %}

{% block form_aside %}
    {{ form_row(form.type) }}
    {{ parent() }}
{% endblock %}

templates/event/edit.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('forms') }}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('forms') }}
{% endblock %}

{% block title %}{{ 'event.form.edit.title'|trans }}{% endblock %}

{% block body %}
    <div class="container">
        <h1>{{ 'event.form.edit.title'|trans }}</h1>

        {{ include('event/_form.html.twig') }}
    </div>
{% endblock %}

templates/event/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}event list{% endblock %}

{% block body %}
    <div class="container">
        <h1>event list</h1>

        <table class="table table-bordered">
            <thead>
            <tr>
                <th>Thema</th>
                <th>Titel</th>
                <th>Art</th>
                <th>Altersspanne</th>
                <th>Schwierigkeit</th>
                <th>Dauer</th>
                <th>Kategorie</th>
                <th>Tags</th>
                <th>letzte Aktualisierung</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% for event in events %}
                <tr>
                    <td>{{ event.topic }}</td>
                    <td>{{ event.title ?? '' }}</td>
                    <td>{{ event.type }}</td>
                    <td>{{ event.age.min }} bis {{ event.age.max }}</td>
                    <td>{{ event.difficulty }}</td>
                    <td>{{ event.duration ? event.duration.format('%d Tage, %H:%I') : '' }}</td>
                    <td>{{ event.category }}</td>
                    <td>{{ event.tags ? event.tags|join(', ') : '' }}</td>
                    <td>{{ event.updatedAt ? event.updatedAt|date('Y-m-d H:i') : '' }}</td>
                    <td>
                        <a href="{{ path('event_show', {'id': event.id}) }}">anzeigen</a>
                        <a href="{{ path('event_edit', {'id': event.id}) }}">bearbeiten</a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="10">Keine Einträge gefunden</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <a href="{{ path('event_new') }}">Neu erstellen</a>
    </div>
{% endblock %}

templates/event/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'event.form.new.title'|trans }}{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('forms') }}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('forms') }}
{% endblock %}

{% block body %}
    <div class="container">
        <h1>{{ 'event.form.new.title'|trans }}</h1>

        {{ include('event/_form.html.twig') }}
    </div>
{% endblock %}

templates/event/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ event.title is null ? event.topic : event.title }} | {{ parent() }}{% endblock %}

{% block body %}
    <div class="container">
        <a href="{{ path('topic_education_index') }}">Zurück zur Liste</a>
        <a class="btn btn-outline-primary float-right" href="{{ path('event_edit', {'id': event.id}) }}">bearbeiten</a>

        <article class="event">
            <header>
                <h1 class="event-title">{{ event.title is null ? event.topic : event.title }} <span class="badge badge-primary">{{ event.type }}</span><span class="badge badge-secondary" style="background-color: #{{ event.category.color }}">{{ event.category }}</span></h1>
                {% if event.tags and event.tags|length > 0 %}<div class="knowledge_point-tags event-tags"><div class="badge badge-tag">{{ event.tags ? event.tags|e|join('</div><div class="badge badge-tag">')|raw : '' }}</div></div>{% endif %}
            </header>

            <div class="row mb-2">
                <div class="col-12 col-md-6">
                    <h2 class="event-meta-title">{{ 'knowledge_point.difficulty.name'|trans }}</h2>
                    <div class="progress meta-progress">
                        <div class="progress-bar" style="width: {{ 1 + event.difficulty * 33 }}%;" role="progressbar" aria-valuenow="{{ event.difficulty }}" aria-valuemin="1" aria-valuemax="3">{{ ('knowledge_point.difficulty.' ~ event.difficulty)|trans }}</div>
                    </div>

                    <h2 class="event-meta-title">{{ 'event.duration.duration'|trans }}</h2>
                    <span class="event-duration">{{ event.duration ? event.duration.format('%d Tag(e), %H:%I') : '' }}</span>
                </div>
                <div class="col-12 col-md-6">
                    <h2 class="event-meta-title">{{ 'knowledge_point.age.age'|trans }}</h2>
                    <div class="progress meta-progress">
                        <div class="progress-bar bg-transparent" style="width: {{ event.age.min * 3.57 + 0.04 }}%;" role="progressbar" aria-valuenow="{{ event.age.min }}" aria-valuemin="0" aria-valuemax=28></div>
                        <div class="progress-bar" style="width: {{ (event.age.max - event.age.min) * 3.57 }}%;" role="progressbar" aria-valuenow="{{ event.age.max }}" aria-valuemin="0" aria-valuemax=28>{{ event.age.min ~ ' bis '|trans ~ (event.age.max == 28 ? '27+' : event.age.max) }}</div>
                    </div>
                </div>
            </div>




            <h2 class="event-meta-title">{{ 'event.content.text'|trans }}</h2>
            <p class="event-text">
                {{ event.text|raw }}
            </p>

            <h2 class="event-meta-title">{{ 'knowledge_point.comment'|trans }}</h2>
            <p class="event-comment">
                {{ event.comment }}
            </p>

            {% if not event.title is null and not event.topic is null %}
                <h2 class="event-meta-title">{{ 'knowledge_point.topic'|trans }}</h2>
                <p class="event-topic">
                    {{ event.topic }}
                </p>
            {% endif %}

            <ul class="nav nav-pills mb-3" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active" id="pills-list-view" data-toggle="tab" href="#list-view" role="tab" aria-controls="list-view" aria-selected="true">Listenansicht</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="pills-table-view" data-toggle="tab" href="#table-view" role="tab" aria-controls="table-view" aria-selected="false">Tabellenansicht</a>
                </li>
            </ul>
            <div class="tab-content" id="pills-zimm-views">
                <div class="tab-pane fade show active" id="list-view" role="tabpanel" aria-labelledby="pills-list-view">
                    {% for entry in event.zimmEntries %}
                        {% include 'event/_card.html.twig' with {'is_form': false, 'entry': entry} %}
                    {% endfor %}
                </div>
                <div class="tab-pane fade" id="table-view" role="tabpanel" aria-labelledby="pills-table-view">
                    <table class="table">
                        <tr><th>Dauer</th><th>Ziel</th><th>Titel</th><th>Beschreibung/Ergänzung</th><th>Material</th></tr>
                        {% for entry in event.zimmEntries %}
                            <tr>
                                <td>{{ entry.duration ? entry.duration.format('%H:%I') : '' }}</td>
                                <td>{{ entry.goal }}</td>
                                <td>
                                    {% if entry.activity %}
                                        <strong><a href="{{ path('activity_show', {'id': entry.activity.id}) }}">{{ entry.title }}</a></strong>
                                    {% else %}
                                        <strong>{{ entry.title }}</strong>
                                    {% endif %}
                                </td>
                                <td>{{ entry.description }}</td>
                                <td>
                                    <ul>
                                        {% for material in entry.materialList %}
                                            {% if not material is empty %}<li>{{ material }}</li>{% endif %}
                                        {% endfor %}
                                    </ul>
                                </td>
                            </tr>
                        {% else %}
                            <tr>
                                <td colspan="4">Keine ZIMM-Einträge gefunden</td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>

            <footer class="mt-3 text-muted">
                <span class="updated-at">{{ 'knowledge_point.updated_at'|trans }}: {{ event.updatedAt ? event.updatedAt|date('Y-m-d H:i:s') : '' }}</span><br>
                <span class="created-at">{{ 'knowledge_point.created_at'|trans }}: {{ event.createdAt ? event.createdAt|date('Y-m-d H:i:s') : '' }}</span>
            </footer>
        </article>
    </div>
{% endblock %}