src/Entity/Activity.php
<?php /** @noinspection PhpDocMissingReturnTagInspection */

namespace App\Entity;

use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use MyCLabs\Enum\Enum;
use Symfony\Component\Validator\Constraints as Assert;
/**
 * Class Event
 * @package App\Entity
 *
 * @ORM\Entity
 * @ORM\Table(name="activities")
 */
class Activity extends KnowledgePoint {
    /**
     * @ORM\Column(type="string")
     */
    private $type;

    /** @ORM\Column(type="string") */
    private $title = '';

    /** @ORM\Column(type="smallint") */
    private $min_people_number;

    /** @ORM\Column(type="smallint") */
    private $max_people_number;

    /** @ORM\Column(type="dateinterval") */
    private $duration;

    /** @ORM\Column(type="text") */
    private $process = '';

    /** @ORM\Column(type="text") */
    private $goal = '';

    /** @ORM\Column(type="string", length=10) */
    private $group_phase;

    /** @ORM\ManyToMany(targetEntity="GenderGroup", cascade={"persist"})
     *  @ORM\JoinTable(name="activity_gendergroup",
     *     joinColumns={@ORM\JoinColumn(name="activity", referencedColumnName="id")},
     *     inverseJoinColumns={@ORM\JoinColumn(name="gender_group", referencedColumnName="id")}
     *     ) */
    private $gender_groups;

    /** @ORM\Column(type="simple_array") */
    private $material_list = [];

    public function getTitle() : string {
        return $this->title;
    }

    public function setTitle(string $title) : self {
        $this->title = $title;
        return $this;
    }

    public function getPeopleNumber() : array {
        return ['min' => $this->min_people_number, 'max' => $this->max_people_number];
    }

    public function setPeopleNumber(array $people_number_range) : self {
        $this->min_people_number = $people_number_range['min'];
        $this->max_people_number = $people_number_range['max'];
        return $this;
    }

    public function getDuration() : ?\DateInterval {
        return $this->duration;
    }

    public function setDuration(\DateInterval $duration) : self {
        $this->duration = $duration;
        return $this;
    }

    public function getProcess() : string {
        return $this->process;
    }

    public function setProcess(string $process) : self {
        $this->process = $process;
        return $this;
    }

    public function getGoal() : string {
        return $this->goal;
    }

    public function setGoal(string $goal) : self {
        $this->goal = $goal;
        return $this;
    }

    public function getGroupPhase() : GroupPhase {
        return new GroupPhase($this->group_phase);
    }

    public function setGroupPhase(GroupPhase $group_phase) : self {
        $this->group_phase = $group_phase;
        return $this;
    }

    public function getGenderGroups() : Collection {
        return $this->gender_groups;
    }

    public function addGenderGroup(GenderGroup $gender_group) : self {
        $this->gender_groups->add($gender_group);
        return $this;
    }

    public function removeGenderGroup(GenderGroup $gender_group) : self {
        $this->gender_groups->removeElement($gender_group);
        return $this;
    }

    public function getType() : ActivityType {
        return new ActivityType($this->type);
    }

    public function setType(ActivityType $type) : self {
        $this->type = $type->getValue();
        return $this;
    }

    /**
     * @throws \Exception
     */
    public function setSection(Section $section) : KnowledgePoint {
        throw new \Exception('Section can not be changed for Activity instances.');
    }

    public function __construct() {
        parent::__construct();
        $this->group_phase = GroupPhase::FORMING();
        $this->gender_groups = new ArrayCollection();
        $this->type = ActivityType::METHOD();
    }

    public function getMaterialList() : array {
        return $this->material_list;
    }

    public function setMaterialList(array $material_list) : self {
        $this->material_list = $material_list;

        return $this;
    }
}

/**
 * Class GroupPhase
 * @package App\Entity
 * @method static GroupPhase FORMING
 * @method static GroupPhase STORMING
 * @method static GroupPhase NORMING
 * @method static GroupPhase PERFORMING
 * @method static GroupPhase REFORMING
 */
class GroupPhase extends Enum {
    private const FORMING = "Forming";
    private const STORMING = "Storming";
    private const NORMING = "Norming";
    private const PERFORMING = "Performing";
    private const REFORMING = "Reforming";
}

/**
 * Class ActivityType
 * @package App\Entity
 * @method static ActivityType METHOD
 * @method static ActivityType GAME
 */
class ActivityType extends Enum {
    private const GAME = "Spiel";
    private const METHOD = "Methode";
}

src/Entity/KnowledgePoint.php
<?php
namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use MyCLabs\Enum\Enum;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Class KnowledgePoint
 * @package App\Entity
 *
 * @ORM\Entity
 * @ORM\Entity(repositoryClass="App\Repository\KnowledgePointRepository")
 * @ORM\InheritanceType("JOINED")
 * @ORM\DiscriminatorColumn(name="discr", type="string")
 * @ORM\DiscriminatorMap({"knowledge_point" = "KnowledgePoint", "activity" = "Activity", "event" = "Event"})
 * @ORM\HasLifecycleCallbacks
 */
class KnowledgePoint {
    /** @ORM\Id @ORM\Column(type="integer") @ORM\GeneratedValue  */
    private $id;

    /** @ORM\Column(type="simple_array", nullable=true) */
    private $tags = [];

    /** @ORM\Column(type="integer") */
    private $min_age;

    /** @ORM\Column(type="integer") */
    private $max_age;

    /** @ORM\Column(type="integer") */
    private $difficulty = 0;

    /** @ORM\Column(type="text") */
    private $comment = '';

    /**
     * @ORM\ManyToOne(targetEntity="User")
     * @ORM\JoinColumn(name="owner_id", referencedColumnName="id")
     */
    private $owner;

    /**
     * @ORM\ManyToOne(targetEntity="Category")
     * @ORM\JoinColumn(name="category_id", referencedColumnName="id")
     */
    private $category;

    /**
     * @ORM\Column(type="integer")
     */
    private $visibility;

    /**
     * @ORM\Column(type="integer")
     */
    private $state;

    /** @ORM\Column(type="datetime") */
    private $createdAt;

    /** @ORM\Column(type="datetime") */
    private $updatedAt;

    /** @ORM\Column(type="string", length=12) */
    private $section;

    public function getAge() : array {
        return ['min' => $this->min_age, 'max' => $this->max_age];
    }

    public function setAge(array $age_range) : self {
        $this->min_age = $age_range['min'];
        $this->max_age = $age_range['max'];
        return $this;
    }

    public function getOwner() : ?User {
        return $this->owner;
    }

    public function setOwner(User $owner) : self {
        $this->owner = $owner;
        return $this;
    }

    public function getVisibility() : Visibility {
        return new Visibility($this->visibility);
    }

    public function setVisibility(Visibility $visibility) : self {
        $this->visibility = $visibility->getValue();
        return $this;
    }

    public function getState() : ModerationState {
        return new ModerationState($this->state);
    }

    public function setState(ModerationState $state) : self {
        $this->state = $state->getValue();
        return $this;
    }

    public function getTags() : array {
        return $this->tags;
    }

    public function setTags(array $tags) : self {
        $this->tags = $tags;
        return $this;
    }

    public function getDifficulty() : int {
        return $this->difficulty;
    }

    public function setDifficulty(int $difficulty) : self {
        $this->difficulty = $difficulty;
        return $this;
    }

    public function getComment() : string {
        return $this->comment;
    }

    public function setComment(string $comment) : self {
        $this->comment = $comment;
        return $this;
    }

    public function getCategory() : ?Category {
        return $this->category;
    }

    public function setCategory(Category $category) : self {
        $this->category = $category;
        return $this;
    }

    public function getId() : int {
        return $this->id;
    }

    public function getUpdatedAt() : \DateTime {
        return $this->updatedAt;
    }

    public function getCreatedAt() : \DateTime {
        return $this->createdAt;
    }

    public function setSection(Section $section) : self {
        $this->section = $section->getValue();
        return $this;
    }

    public function getSection() : Section {
        return new Section($this->section);
    }

    public function __construct() {
        // Set Defaults
        $this->visibility = Visibility::PRIVATE();
        $this->state = ModerationState::UNMODERATED();
        $this->section = Section::EDUCATION();
    }

    /**
     * @ORM\PrePersist
     */
    public function onPrePersist() : void {
        $this->createdAt = new \DateTime();
        $this->updatedAt = $this->createdAt;
    }

    /**
     * @ORM\PreUpdate
     */
    public function onPreUpdate() : void {
        $this->updatedAt = new \DateTime();
    }

    public function getClass() {
        return get_class($this);
    }
}

/**
 * Class Visibility
 * @package App\Entity
 * @method static Visibility PUBLIC
 * @method static Visibility PRIVATE
 * @method static Visibility AUTHENTICATED
 */
class Visibility extends Enum {
    private const PUBLIC = 0;
    private const PRIVATE = 1;
    private const AUTHENTICATED = 2;
}

/**
 * Class ModerationState
 * @package App\Entity
 * @method static ModerationState UNMODERATED
 * @method static ModerationState MODERATION_PENDING
 * @method static ModerationState PUBLISHED
 */
class ModerationState extends Enum {
    private const UNMODERATED = 0;
    private const MODERATION_PENDING = 1;
    private const PUBLISHED = 2;
}

/**
 * Class Section
 * @package App\Entity
 * @method static Section THEORY
 * @method static Section EDUCATION
 * @method static Section ORGANISATION
 */
class Section extends Enum {
    private const THEORY = 'theory';
    private const EDUCATION = 'education';
    private const ORGANISATION = 'organisation';
}

src/Form/Type/ActivityType.php
<?php

namespace App\Form\Type;

use App\Entity\Activity;
use App\Entity\GenderGroup;
use App\Entity\GroupPhase;
use Psr\Log\LoggerInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateIntervalType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Contracts\Translation\TranslatorInterface;

class ActivityType extends AbstractType {
    private $t;
    private $logger;

    public function __construct(TranslatorInterface $t, LoggerInterface $logger) {
        $this->t = $t;
        $this->logger = $logger;
    }

    public function buildForm(FormBuilderInterface $builder, array $options) {
        $t = $this->t;

        $builder
            ->add('type', EnumType::class, [
                'enum_class' => \App\Entity\ActivityType::class,
                'label' => 'activity.meta.type',
                'required' => true,
            ])
            ->add('title', TextType::class, [
                'attr' => [
                    'placeholder' => 'activity.meta.title',
                ],
                'label' => 'activity.meta.title',
                'required' => true,
            ])
            ->add('people_number', FromToRangeType::class, [
                'min' => 0,
                'max' => 30,
                'label_format' => 'activity.meta.people_number.%name%',
                'marks' => [
                    0 => '0',
                    5 => '5',
                    10 => '10',
                    20 => '20',
                    30 => '30+',
                ],
                'required' => false,
            ])
            ->add('duration', DateIntervalType::class, [
                'widget' => 'integer', // render a text field for each part
                'with_years' => false,
                'with_months' => false,
                'with_days' => false,
                'with_hours' => true,
                'with_minutes' => true,
                'label_format' => 'activity.meta.duration.%name%',
                'required' => true,
            ])
            ->add('process', QuillType::class, [
                'placeholder' => $t->trans('activity.form.content.process_placeholder'),
                'label' => 'activity.content.process',
                'required' => false,
            ])
            ->add('goal', TextType::class, [
                'label' => 'activity.content.goal',
                'required' => false,
            ])
            ->add('group_phase', EnumType::class, [
                'enum_class' => GroupPhase::class,
                'label' => 'activity.meta.group_phase',
                'required' => false,
            ])
            ->add('material_list', SimpleArrayType::class, [
                'label' => 'activity.content.material',
                'required' => false,
            ]) // TODO: Make tag-like entry
            ->add('gender_groups', EntityType::class, [
                'class' => GenderGroup::class,
                'multiple' => true,
                'label' => 'activity.meta.gender_groups',
                'required' => false,
            ])
        ;
    }

    public function getParent() {
        return KnowledgePointType::class;
    }

    public function configureOptions(OptionsResolver $resolver) {
        $resolver->setDefaults([
            'data_class' => Activity::class,
        ]);
    }
}

src/Controller/ActivityController.php
<?php

namespace App\Controller;

use App\Entity\Activity;
use App\Form\Type\ActivityType;
use Limenius\Liform\Liform;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/activity")
 */
class ActivityController extends AbstractController {
    private $liform;

    public function __construct(Liform $liform) {
        $this->liform = $liform;
    }

    /**
     * @Route("/", name="activity_index", methods={"GET"})
     */
    public function index() : Response {
        $activities = $this->getDoctrine()
            ->getRepository(Activity::class)
            ->findAll();

        return $this->render('activity/list.html.twig', [
            'activities' => $activities,
            'current_topic' => 'education',
        ]);
    }

    /**
     * @Route("/new", name="activity_new", methods={"GET","POST"})
     */
    public function new(Request $request) : Response {
        $activity = new Activity();
        $form = $this->createForm(ActivityType::class, $activity);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($activity);
            $entityManager->flush();

            return $this->redirectToRoute('activity_show', [
                'id' => $activity->getId(),
            ]);
        }

        return $this->render('activity/new.html.twig', [
            'activity' => $activity,
            'form' => $form->createView(),
            'current_topic' => 'education',
        ]);
    }

    /**
     * @Route("/{id}", name="activity_show", methods={"GET"})
     */
    public function show(Activity $activity) : Response {
        return $this->render('activity/show.html.twig', [
            'activity' => $activity,
            'current_topic' => 'education',
        ]);
    }

    /**
     * @Route("/{id}/edit", name="activity_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Activity $activity) : Response {
        $form = $this->createForm(ActivityType::class, $activity, ['csrf_protection' => false]);
        $serializer = $this->get('serializer');
        $initial_values = $serializer->normalize($form);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('activity_show', [
                'id' => $activity->getId(),
            ]);
        }

        return $this->render('activity/edit.html.twig', [
            'activity' => $activity,
            'form' => $form->createView(),
            'initial_values' => $initial_values,
            'current_topic' => 'education',
        ]);
    }

    /**
     * @Route("/{id}", name="activity_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Activity $activity) : Response {
        if($this->isCsrfTokenValid('delete' . $activity->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($activity);
            $entityManager->flush();
        }

        return $this->redirectToRoute('activity_index');
    }
}

templates/activity/_delete_form.html.twig
<form method="post" action="{{ path('activity_delete', {'id': activity.id}) }}" onsubmit="return confirm('Bist du sicher, dass du die Aktivität löschen möchtest?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ activity.id) }}">
    <button class="btn">Löschen</button>
</form>

templates/activity/_form.html.twig
{% extends 'form/knowledge_point.common.html.twig' %}

{% block form_content %}
    <h2>{{ 'activity.form.content.title'|trans }}</h2>
        {{ form_row(form.goal) }}
        {{ form_row(form.process) }}
        {{ form_row(form.comment) }}
        {{ form_row(form.material_list) }}
    <h2>{{ 'activity.form.meta.title'|trans }}</h2>
    <div class="row">
        <div class="col-6">
            {{ form_row(form.duration) }}
            {{ form_row(form.age) }}
            {{ form_row(form.people_number) }}
        </div>
        <div class="col-6">
            {{ form_row(form.difficulty) }}
            {{ form_row(form.group_phase) }}
            {{ form_row(form.gender_groups) }}
        </div>
    </div>
{% endblock %}

{% block form_aside %}
    {{ form_row(form.type) }}
    {{ parent() }}
{% endblock %}

templates/activity/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'activity.form.edit.title'|trans }}{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('forms') }}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('forms') }}
{% endblock %}

{% block body %}
    <div class="container" id="limenius" data-initial-values="{{ initial_values|json_encode }}">
        <h1>{{ 'activity.form.edit.title'|trans }}</h1>

        {{ include('activity/_form.html.twig') }}
    </div>
{% endblock %}

templates/activity/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}Activity list{% endblock %}

{% block body %}
    <div class="container">
        <h1>Activity list</h1>

        <table class="table table-bordered">
            <thead>
            <tr>
                <th>Ziel</th>
                <th>Titel</th>
                <th>Art</th>
                <th>Altersspanne</th>
                <th>Schwierigkeit</th>
                <th>TN Anzahl</th>
                <th>Dauer</th>
                <th>Gruppenphase</th>
                <th>Geschlechtergruppen</th>
                <th>Kategorie</th>
                <th>Tags</th>
                <th>letzte Aktualisierung</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% for activity in activities %}
                <tr>
                    <td>{{ activity.goal }}</td>
                    <td>{{ activity.title }}</td>
                    <td>{{ activity.type }}</td>
                    <td>{{ activity.age.min }} bis {{ activity.age.max }}</td>
                    <td>{{ activity.difficulty }}</td>
                    <td>{{ activity.peopleNumber.min }} bis {{ activity.peopleNumber.max }}</td>
                    <td>{{ activity.duration ? activity.duration.format('%H:%I') : '' }}</td>
                    <td>{{ activity.groupPhase }}</td>
                    <td>{{ activity.genderGroups ? activity.genderGroups|join(', ') : '' }}</td>
                    <td>{{ activity.category }}</td>
                    <td>{{ activity.tags ? activity.tags|join(', ') : '' }}</td>
                    <td>{{ activity.updatedAt ? activity.updatedAt|date('Y-m-d H:i') : '' }}</td>
                    <td>
                        <a href="{{ path('activity_show', {'id': activity.id}) }}">anzeigen</a>
                        <a href="{{ path('activity_edit', {'id': activity.id}) }}">bearbeiten</a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="13">Keine Einträge gefunden</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <a href="{{ path('activity_new') }}">Neu erstellen</a>
    </div>
{% endblock %}

templates/activity/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'activity.form.new.title'|trans }}{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('forms') }}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('forms') }}
{% endblock %}

{% block body %}
    <div class="container">
        <h1>{{ 'activity.form.new.title'|trans }}</h1>

        {{ include('activity/_form.html.twig') }}
    </div>
{% endblock %}

templates/activity/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Activity{% endblock %}

{% block body %}
    <div class="container">
        <a href="{{ path('topic_education_index') }}">Zurück zur Liste</a>
        <a class="btn btn-outline-primary float-right" href="{{ path('activity_edit', {'id': activity.id}) }}">bearbeiten</a>

        <article class="activity">
            <header>
                <h1 class="activity-title">{{ activity.title }} <span class="badge badge-primary">{{ activity.type }}</span><span class="badge badge-secondary" style="background-color: #{{ activity.category.color }}">{{ activity.category }}</span></h1>
                {% if activity.tags and activity.tags|length > 0 %}<div class="knowledge_point-tags activity-tags"><div class="badge badge-tag">{{ activity.tags ? activity.tags|e|join('</div><div class="badge badge-tag">')|raw : '' }}</div></div>{% endif %}
            </header>

            <div class="row mb-2">
                <div class="col-12 col-md-6">
                    <h2 class="activity-meta-title">{{ 'knowledge_point.difficulty.name'|trans }}</h2>
                    <div class="progress meta-progress">
                        <div class="progress-bar" style="width: {{ 1 + activity.difficulty * 33 }}%;" role="progressbar" aria-valuenow="{{ activity.difficulty }}" aria-valuemin="1" aria-valuemax="3">{{ ('knowledge_point.difficulty.' ~ activity.difficulty)|trans }}</div>
                    </div>

                    <h2 class="activity-meta-title">{{ 'event.duration.duration'|trans }}</h2>
                    <span class="event-duration">{{ activity.duration ? activity.duration.format('%d Tag(e), %H:%I') : '' }}</span>
                </div>
                <div class="col-12 col-md-6">
                    <h2 class="activity-meta-title">{{ 'knowledge_point.age.age'|trans }}</h2>
                    <div class="progress meta-progress">
                        <div class="progress-bar bg-transparent" style="width: {{ activity.age.min * 3.57 + 0.04 }}%;" role="progressbar" aria-valuenow="{{ activity.age.min }}" aria-valuemin="0" aria-valuemax=28></div>
                        <div class="progress-bar" style="width: {{ (activity.age.max - activity.age.min) * 3.57 }}%;" role="progressbar" aria-valuenow="{{ activity.age.max }}" aria-valuemin="0" aria-valuemax=28>{{ activity.age.min ~ ' bis '|trans ~ (activity.age.max == 28 ? '27+' : activity.age.max) }}</div>
                    </div>

                    <h2 class="activity-meta-title">{{ 'activity.meta.people_number.people_number'|trans }}</h2>
                    <div class="progress meta-progress">
                        <div class="progress-bar bg-transparent" style="width: {{ activity.peopleNumber.min * 3.3 + 0.1 }}%;" role="progressbar" aria-valuenow="{{ activity.peopleNumber.min }}" aria-valuemin="0" aria-valuemax=30></div>
                        <div class="progress-bar" style="width: {{ (activity.peopleNumber.max - activity.peopleNumber.min) * 3.3 }}%;" role="progressbar" aria-valuenow="{{ activity.peopleNumber.max }}" aria-valuemin="0" aria-valuemax=30>{{ activity.peopleNumber.min ~ ' bis '|trans ~ (activity.peopleNumber.max == 30 ? '30+' : activity.peopleNumber.max) }}</div>
                    </div>
                </div>
                <div class="col-12 col-md-6 mt-2">
                    <h2 class="activity-meta-title">{{ 'activity.content.goal'|trans }}</h2>
                    <p class="activity-goal">
                        {{ activity.goal }}
                    </p>

                    <h2 class="activity-meta-title">{{ 'activity.meta.gender_groups'|trans }}</h2>
                    <p class="activity-goal">
                        {{ activity.genderGroups ? activity.genderGroups|join(', ') : '' }}
                    </p>
                </div>
                <div class="col-12 col-md-6 mt-2">
                    <h2 class="activity-meta-title">{{ 'activity.meta.group_phase'|trans }}</h2>
                    <p class="activity-group-phase">
                        {{ activity.groupPhase }}
                    </p>
                </div>
            </div>


            <h2 class="activity-meta-title">{{ 'knowledge_point.comment'|trans }}</h2>
            <p class="activity-comment">
                {{ activity.comment }}
            </p>

            <h2 class="activity-meta-title">{{ 'activity.content.process'|trans }}</h2>
            <p class="activity-process">
                {{ activity.process|raw }}
            </p>

            {% if activity.materialList %}
                <h2 class="activity-meta-title">{{ 'activity.content.material'|trans }}</h2>
                <ul>
                    {% for material in activity.materialList %}
                        {% if not material is empty %}<li>{{ material }}</li>{% endif %}
                    {% endfor %}
                </ul>
            {% endif %}

            <footer class="mt-3 text-muted">
                <span class="updated-at">{{ 'knowledge_point.updated_at'|trans }}: {{ activity.updatedAt ? activity.updatedAt|date('Y-m-d H:i:s') : '' }}</span><br>
                <span class="created-at">{{ 'knowledge_point.created_at'|trans }}: {{ activity.createdAt ? activity.createdAt|date('Y-m-d H:i:s') : '' }}</span>
            </footer>
        </article>
    </div>
{% endblock %}